version: '3.7'
services:
  polygon-etherenum-nextjs-marketplace:
    image: 'polygon-etherenum-nextjs-marketplace'
    container_name: 'polygon-etherenum-nextjs-marketplace'
    networks:
      server:
        ipv4_address: 10.1.0.14
    ports:
      - '0.0.0.0:4000:3000'
  ipfs: 
    image: 'ipfs/go-ipfs:latest'
    container_name: 'ipfs'
    networks:
      server:
        ipv4_address: 10.1.0.8
    ports:
      - '0.0.0.0:4001:4001'
      - '0.0.0.0:8080:8080'
      - '0.0.0.0:5001:5001'
    volumes:
      - './ipfs/export:/export'
      - './ipfs/data:/data/ipfs'
networks:
  server:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
